# server:
#   port: ${PORT:8080}       # Railway dynamic port
#   address: 0.0.0.0         # Bind to all network interfaces

# spring:
#   datasource:
#     url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#     username: ${PGUSER}
#     password: ${PGPASSWORD}
#     driver-class-name: org.postgresql.Driver
#     hikari:
#       maximum-pool-size: 10
#       minimum-idle: 2

#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update
#     show-sql: false
#     open-in-view: false

#   liquibase:
#     enabled: 

# management:
#   endpoints:
#     enabled-by-default: false

# jwt:
#   secret: ${JWT_SECRET}       # Must be set in Railway Environment Variables
#   expiration: 86400000

# logging:
#   level:
#     root: INFO
#     com.mvgore.garageapi: INFO

# # Optional: track Railway environment for debugging/logging
# railway:
#   project-name: ${RAILWAY_PROJECT_NAME}
#   environment: ${RAILWAY_ENVIRONMENT_NAME}
#   service-name: ${RAILWAY_SERVICE_NAME}
#   project-id: ${RAILWAY_PROJECT_ID}
#   environment-id: ${RAILWAY_ENVIRONMENT_ID}
#   service-id: ${RAILWAY_SERVICE_ID}



######LOCATHOST SERVER ##########

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garage_db
    username: postgres
    password: garage_database
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # IMPORTANT â†’ Liquibase controls schema
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
