server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  liquibase:
    enabled: false

management:
  endpoints:
    enabled-by-default: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: OFF
    com.mvgore.garageapi: INFO


######LOCATHOST SERVER ########

# server:
#   port: 8080

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/garage-api
#     username: postgres
#     password: 1234
#     driver-class-name: org.postgresql.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     open-in-view: true
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         use_sql_comments: true

# jwt:
#   secret: local-dev-secret
#   expiration: 86400000

# logging:
#   level:
#     root: DEBUG

#     # Spring Framework internals
#     org.springframework: DEBUG
#     org.springframework.boot: DEBUG
#     org.springframework.web: DEBUG
#     org.springframework.jdbc: DEBUG

#     # Hibernate & DB
#     org.hibernate: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type: TRACE
#     com.zaxxer.hikari: DEBUG

#     # Tomcat
#     org.apache.catalina: DEBUG
#     org.apache.tomcat: DEBUG

#     # Your app
#     com.mvgore.garageapi: DEBUG

#   pattern:
#     console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
