server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  liquibase:
    enabled: false   # IMPORTANT → Liquibase logs a LOT

management:
  endpoints:
    enabled-by-default: false   # Disable actuator spam completely

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: OFF

    # Spring internals
    org.springframework: OFF
    org.springframework.boot: OFF
    org.springframework.web: OFF
    org.springframework.jdbc: OFF

    # Hibernate & DB
    org.hibernate: OFF
    com.zaxxer.hikari: OFF

    # Tomcat
    org.apache.catalina: OFF
    org.apache.tomcat: OFF

    # Actuator
    org.springframework.boot.actuate: OFF

    # ✅ YOUR APPLICATION ONLY
    com.mvgore.garageapi: INFO

  pattern:
    console: "%msg%n"
